print("Pranika Shrestha")
print("This is day 1 \t Lets begin")
print("I love to read books, write stories and poems, dance, eat, and sleep.")
print("This is a daily challenge I am committed to.")
print("I will try to use which helps to break a line \n like this.")
print("I wish to learn something good \t haha this is like writing a diary but in code.")
print("I don't know what to write, I am thinking of food.")
print("I hope i learn something from this.")
print("I am reading a book by fyodor dovestsky \t I know that name's hard.")
print("okay, this is last bye!!!")
print("lemme try this" "i can do this right?" "\n i have totally forgot how to write code")